{% set version = "5.6.2" %}

package:
  name: podman
  version: {{ version }}

source:
  url: https://github.com/containers/podman/archive/v{{ version }}.tar.gz
  sha256: c6de8f347ee93e4626d7c82e3adcb1b34e64175b5ca9959e790e52a0b4bbf2a1
  folder: src/github.com/containers/podman
  patches:
    # NOTE: This adds the memfd_create syscall which is not available on CentOS 6's kernels.
    - 0001-Add-missing-defines-for-CentOS-6.patch
    # NOTE: If the patch for relative paths stops working, see the buildah
    #       feedstock for an alternative with an hardcoded prefix path.
    - 0002-relative-paths-for-system-config-and-binaries.patch

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('go-cgo') }} 1.23
    # Instead specify the underlying packages since this isn't cross-platform
    - go-licenses >=0.0.44
    - go-md2man
    - pkg-config
    - make
  host:
    - btrfs-progs
    - containers-common
    - glib
    # Header+pkgconfig files for libglib are in the glib package.
    - libglib
    - gpgme
    - libassuan
    - libgpg-error
    - libseccomp
  run:
    - conmon >=2.0.30
    - containers-common
    - cni-plugins
    # TODO: switch to crun?
    - runc
    - slirp4netns
    - netavark

test:
  requires:
    # NOTE: Some binaries from util-linux, like `nsenter`, are needed. To avoid
    #       clashes with users' system-provided base utils, let's not add
    #       util-linux to requirements/run for now.
    - util-linux

about:
  home: https://podman.io/
  dev_url: https://github.com/containers/podman
  doc_url: https://docs.podman.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/github.com/containers/podman/LICENSE
    - license-files/
  summary: 'Podman: A tool for managing OCI containers and pods.'
  description: >
    Podman (the POD MANager) is a tool for managing containers and images, volumes mounted into those containers, and pods made from groups of containers. Podman is based on libpod, a library for container lifecycle management that is also contained in this repository. The libpod library provides APIs for managing containers,
    pods, container images, and volumes.

extra:
  recipe-maintainers:
    - mbargull
    - dhirschfeld
    - manics
    - xhochy
